server:
  port: 8008

spring:
  h2:
    console:
      path: /console
      enabled: true
  datasource:
    url: jdbc:h2:mem:employeeData
    driverClassName: org.h2.Driver
    username: username
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


